### ISSUE TITLE
database or disk is full ( code 13 SQLITE_FULL)

### ISSUE THREAD

**Issue by LouieVP** [VerusCoin/Verus-Mobile#110]
"database or disk is full ( code 13 SQLITE_FULL)" on Verus Mobile latest release 0.3.0_1.apk  I also had earlier version of Verus Mobile, same code.  I have adequate storage on Android phone.

**Comment by michaeltout** [comment]
Hi, thanks for reporting this, it should be resolved in v0.3.0-24, please update and let me know if the issue persists

**Comment by LouieVP** [comment]
The newest version fixed the Code 13 issue, works great now! Thanks for your hard work. ☺

**Comment by michaeltout** [comment]
Happy to hear it :)
