### ISSUE TITLE
 Adding USDT, EURT (ERC-20) conversion 

### ISSUE THREAD

**Issue by Kabingeran** [VerusCoin/Verus-Mobile#150]
Hi

It would be logical to add conversion to the main stablecoins: USDT, EURT (ERC-20).

**Comment by michaeltout** [comment]
Hi, Verus is a completely decentralised network where any network participant can bridge over ERC20 currencies and create currency baskets to allow bridged currencies to be converted between each other. The Verus Mobile app is an open source, non-custodial wallet interface to this network, so if someone on the Verus network were to bridge the currencies you mention and create currency baskets to make them convertible to other currencies, the wallet would automatically support them.
