### ISSUE TITLE
Sending KMD on mobile

### ISSUE THREAD

**Issue by Oink70** [VerusCoin/Verus-Mobile#54]
snippet from KMD discord:

> Claiming in mobile should be no issue, at least not to my knowledge. There's no specific claim button, but sending your entire balance to your own address is what any claim button would do.

> Ok this is what I get when trying to send balance to myself
> **Error: Can’t find variable:total interestUTXOcount**

The send fails.

The user had not sent his funds (or claimed rewards) in 11 months.
Confirmed on my own address on iOS mobile, with funds that claimed rewards just 11 days ago using native.

**Comment by michaeltout** [comment]
Thanks for the report! Should be fixed here and released in the next upcoming version https://github.com/VerusCoin/Verus-Mobile/commit/74f5c2ecd8df1198e1d8a737ce8d362435becdb2
