### ISSUE TITLE
Connection Issue/Error with Samsung Knox

### ISSUE THREAD

**Issue by jyspyjokerdad** [VerusCoin/Verus-Mobile#65]
![Screenshot_20210326-155459_Verus Mobile](https://user-images.githubusercontent.com/81404415/112587403-70248680-8e4d-11eb-9c27-e820c3536482.jpg)

Little unsure here if this is a connection issue with the Node itself or if Samsung Knox is completely blocking the connection since the App is still in beta and hasn't been officially signed by Google Play yet. If someone could help that'd be great as I've got funds that have "apparently" been sent to my Mobile Verus Wallet

**Comment by modmini** [comment]
> ![Screenshot_20210326-155459_Verus Mobile](https://user-images.githubusercontent.com/81404415/112587403-70248680-8e4d-11eb-9c27-e820c3536482.jpg)
> 
> Little unsure here if this is a connection issue with the Node itself or if Samsung Knox is completely blocking the connection since the App is still in beta and hasn't been officially signed by Google Play yet. If someone could help that'd be great as I've got funds that have "apparently" been sent to my Mobile Verus Wallet

**Comment by michaeltout** [comment]
I appreciate the report but both pictures posted here are from an older, deprecated version of Verus Mobile, please update to the latest mandatory update (0.2.2), and see if the problem persists.
