### ISSUE TITLE
Address tidak terbaca 

### ISSUE THREAD

**Issue by Defrizon28** [VerusCoin/Verus-Mobile#83]
Address tidak terbaca dan verus wallet tidak masuk  : REzvbhExEmjYbys4KYVKDxFCezrDASvyCG

![Screenshot_20210918_130706](https://user-images.githubusercontent.com/90947870/133878179-c5cc61e2-9aab-4e39-b368-a8dc0761ce3e.jpg)

**Comment by michaeltout** [comment]
Please use the discord at verus.io/discord for support, there are international language channels there where a community member might be able to assist.
